import { createHash, randomUUID } from 'node:crypto';
import { pool } from '../db/pool.js';
import { HttpError } from '../utils/http.js';
export async function vote(req,res){ const abuseKey=createHash('sha256').update(`${req.ip}|${req.headers['user-agent']||''}|coopera`).digest('hex'); try{await pool.query('INSERT INTO votes(id,user_id,abuse_key) VALUES (?,?,?)',[randomUUID(),req.user.id,abuseKey]);}catch(e){if(e.code==='ER_DUP_ENTRY')throw new HttpError(409,'Seu voto já foi registrado — uma pessoa, uma voz.');throw e;} const [[row]]=await pool.query('SELECT COUNT(*) total FROM votes');res.status(201).json({message:'Seu voto foi registrado. Obrigado por participar.',total:Number(row.total)}); }
export async function voteStatus(req,res){ const [[row]]=await pool.query('SELECT COUNT(*) total FROM votes'); res.json({total:Number(row.total)}); }
export async function transparency(_req,res){ const [items]=await pool.query('SELECT id,kind,title,description,amount_cents,status,occurred_on FROM transparency_updates WHERE published=1 ORDER BY occurred_on DESC'); const [[funds]]=await pool.query("SELECT COALESCE(SUM(amount_cents),0) total_cents FROM contributions WHERE status='confirmed'"); res.json({totalRaisedCents:Number(funds.total_cents),items}); }
export async function contribution(_req,res){ res.status(503).json({enabled:false,message:'Contribuições financeiras ainda não estão habilitadas. Nenhuma cobrança foi realizada.'}); }
export async function report(req,res){ await pool.query('INSERT INTO reports(id,reporter_id,reported_user_id,post_id,reason,details) VALUES (?,?,?,?,?,?)',[randomUUID(),req.user.id,req.validated.reportedUserId||null,req.validated.postId||null,req.validated.reason,req.validated.details||null]); res.status(201).json({message:'Denúncia recebida. Nossa moderação fará a análise.'}); }
export async function block(req,res){ if(req.params.userId===req.user.id) throw new HttpError(400,'Não é possível bloquear sua própria conta.'); await pool.query('INSERT IGNORE INTO blocks(blocker_id,blocked_id) VALUES (?,?)',[req.user.id,req.params.userId]); res.status(204).end(); }
